### ISSUE TITLE
Filters request

### ISSUE THREAD

**Issue by wangjingyu7** [MicronOxford/SpekCheck#100]
I repeat my request in the closed issue. Please feel free to close it once done. Thanks!

Can we add ZT405/488/561/647rpc and ZET405/488/561/640mv2 to the filter list? 

_Originally posted by @wangjingyu7 in https://github.com/MicronOxford/SpekCheck/issues/94#issuecomment-659511678_

**Comment by iandobbie** [comment]
These filters are both in the main repository, do you want new setups configured for the 4pi with them? If so I will do that before asking david to update the running version of spekcheck

**Comment by iandobbie** [comment]
This has been done just awaiting David to upload to the running server
