### ISSUE TITLE
Filter FF01-676/37-25

### ISSUE THREAD

**Issue by wangjingyu7** [MicronOxford/SpekCheck#104]
Hi David/Ian, 
Could you added another filter, FF01-676/37-25 to the list? Thanks.
Jingyu

**Comment by iandobbie** [comment]
Yes of course jingyu but you can also add filters etc. The filters, dyes etc are all in the main spekcheck GitHub repository. The setups files are in a different repository. You need the spectral data formatted as csv with a small header, see the existing filters or dyes for an example. Any new files also need to be added to the relevant .json file. I do this by running make in the main directory which updates all the json files except the setups.json.

Ian

Sent from my iPhone

On 9 Nov 2020, at 14:00, Jingyu.Wang <notifications@github.com> wrote:

﻿

Hi David/Ian,
Could you added another filter, FF01-676/37-25 to the list? Thanks.
Jingyu

**Comment by iandobbie** [comment]
This has been done so closing
