### ISSUE TITLE
Dyes lacking QE or EC give cryptic NaN output.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/SpekCheck#69]
If a dye lacks a QE or EC then the interface still displayes "brightness=NaN", not exactly clear. can we have some other indication?

**Comment by carandraug** [comment]
The NaN was on purpose. I made sure that a NaN gets through instead of an error.  Would a dash be better?

**Comment by carandraug** [comment]
I thought this issue was about NaN on the table of optimised dyes but it was actually about showing NaN on the title of the plots.

Fixed so it does not include brightness on the title if brightness is NaN.
