### ISSUE TITLE
Peak QE of the human eye is .1 to .3

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/SpekCheck#70]
As we have CCD, sCMOS etc as real QE we should do the same for the eye. Quick trawl of google turns up https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3831599/ with this number in it.  I will scale the files

**Comment by iandobbie** [comment]
Further reading of the above paper implies that the absolute QE is in the 8% range, although concious detection is much lower. I will scale the curve to peak at 8%.

**Comment by iandobbie** [comment]
These files are scaled in #72 with reference to paper above and https://www.wikilectures.eu/w/Spectral_sensitivity_of_the_human_eye which says cones are 1% as sensitive as rods.

**Comment by carandraug** [comment]
merged #72 so closing issue
