### ISSUE TITLE
Carinas comments

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/SpekCheck#73]
this is what I've found:

_ weird horizontal lines on the left/right still appear whenever data reaches 300 and 800 nm. 

_ Help: 

* Excitation Efficiency is empty
* Local installation is missing for Safari
* File Format: empty
* Don't forget the note: I don't like qe for column name.
* Example files: for an ignorant like me, it's not clear when we need double # for comments, or only
 single #. 

_ Customised filters: crosses to delete filters do not work; R/T works for emission path and not
excitation. 

Carina

**Comment by iandobbie** [comment]
I think Carina doesn't quite understand the RT controls and the excitation path. works fine on chrome and safari on my machine. All it does is reduce the ex efficiency and reflect this in the excitation spectra curve.

**Comment by carandraug** [comment]
> I think Carina doesn't quite understand the RT controls and the excitation path. works fine on chrome and safari on my machine. All it does is reduce the ex efficiency and reflect this in the excitation spectra curve.

She does.  There was a real issue which I fixed yesterday. Basically Array.concat is a class method in Firefox but in Chrome is an instance method only.  We use Array.concat when removing filters from the filterstack which caused it to fail in Chrome.

**Comment by carandraug** [comment]
I'm going through this list and we are missing the instructions how to enable local applications to access local files on Safari.  Ian, can you confirm that this is the correct method? https://ccm.net/faq/36342-safari-how-to-enable-local-file-access

**Comment by iandobbie** [comment]
These are all covered I think

**Comment by carandraug** [comment]
> These are all covered I think

We are still missing the link with instructions for Safari.  Have you found anything good and confirmed that works?

**Comment by iandobbie** [comment]
Carnë Draug <notifications@github.com> writes:

>  These are all covered I think
>
> We are still missing the link with instructions for Safari. Have you found anything good and confirmed
> that works?

Yes, I thought I had sent it to you.

I will find it again.

Ian

**Comment by carandraug** [comment]
I have been looking for links for Safari and seems like there's nothing official looking.  Also all instructions require enabling developer options which have a system-wide permanent effect instead of only affecting one session.  So I'm thinking that maybe for Safari we just recommend the python simple server.  What do you think?

**Comment by carandraug** [comment]
We changed the help text to recommend running a simple web server instead for the case of safari and chrome. See e0f7561d8

All issues have now been addressed so closing issue as fixed.
