### ISSUE TITLE
Salvaged fluorescence mode.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/SpekCheck#94]
We should have a method of adding a salvaged fluorescence mode to calculate the fractional intensity of a dye transmitted to a normal detector path and also the fraction salvaged from the dichroic to see if two dye are likely to be separable or not.

**Comment by iandobbie** [comment]
As the paths will have different components, as well as some commonality further thinking on this make me think it is better to just have it as a separate "setup" definition. I have done this for the 4pi with the 4pi farred config for the conventional imaging path and the 4pi farred salvaged for the salvaged fluorescence path.

**Comment by wangjingyu7** [comment]
Can we add ZT405/488/561/647rpc and ZET405/488/561/640mv2 to the filter list? Thanks!

**Comment by wangjingyu7** [comment]
Do I need to open a new issue?
